#!/usr/bin/env node
/**
 * Writes packages/doichain/tailwind-preset.cjs: the colour palette as CSS
 * variables, light and dark, so every existing class — bg-white, text-gray-900,
 * text-red-600 — follows the theme without a single `dark:` twin.
 *
 * Why this way: the lessons carry 350 colour classes in 24 files. Twins for all
 * of them would be 350 edits, and every class written later would need one too;
 * forgetting it is silent (simple-todo lived through exactly that). Here the
 * palette is the theme, and a new class is themed the moment it is written.
 *
 * Light is Tailwind's own palette. Dark:
 *  - neutrals (white, gray) follow a hand-set scale, the same family as the
 *    review pages: ground #0E1419, surfaces a step lighter, text #E2E9EE;
 *  - accents mirror their scale (50↔950, 100↔900 … 500 stays), so text-red-600
 *    becomes a light red on a dark ground and bg-amber-50 a dark amber tint.
 *
 * Run: node scripts/build-theme.mjs   (re-run after changing the families below)
 */
import { createRequire } from 'node:module';
import { writeFileSync } from 'node:fs';

const require = createRequire(new URL('../apps/lesson01/', import.meta.url));
const tw = require('tailwindcss/colors');

const ACCENTS = [
	'red',
	'orange',
	'amber',
	'yellow',
	'green',
	'emerald',
	'sky',
	'blue',
	'indigo',
	'violet',
	'purple'
];
const SHADES = ['50', '100', '200', '300', '400', '500', '600', '700', '800', '900', '950'];
const MIRROR = Object.fromEntries(SHADES.map((s, i) => [s, SHADES[SHADES.length - 1 - i]]));

const DARK_NEUTRAL = {
	white: '#0E1419',
	black: '#F4F7F9',
	gray: {
		50: '#141C23',
		100: '#1A242C',
		200: '#26333C',
		300: '#3E4F5B',
		400: '#6B7A84',
		500: '#83939E',
		600: '#A3B1BB',
		700: '#C2CCD3',
		800: '#D7DEE3',
		900: '#E2E9EE',
		950: '#F1F5F8'
	}
};

const channels = (hex) => {
	const h = hex.replace('#', '');
	return [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16)).join(' ');
};

const light = {},
	dark = {},
	colors = {};
const add = (name, lightHex, darkHex) => {
	const v = `--c-${name}`;
	light[v] = channels(lightHex);
	dark[v] = channels(darkHex);
	return `rgb(var(${v}) / <alpha-value>)`;
};

colors.white = add('white', tw.white, DARK_NEUTRAL.white);
colors.black = add('black', tw.black, DARK_NEUTRAL.black);
colors.gray = Object.fromEntries(
	SHADES.map((s) => [s, add(`gray-${s}`, tw.gray[s], DARK_NEUTRAL.gray[s])])
);
for (const family of ACCENTS)
	colors[family] = Object.fromEntries(
		SHADES.map((s) => [s, add(`${family}-${s}`, tw[family][s], tw[family][MIRROR[s]])])
	);

const block = (vars) =>
	Object.entries(vars)
		.map(([k, v]) => `\t\t\t\t'${k}': '${v}'`)
		.join(',\n');

const out = `/**
 * Generated by scripts/build-theme.mjs — do not edit by hand, re-run the script.
 *
 * The colour palette as CSS variables, light under :root and dark under .dark,
 * so every colour class follows the theme. See the script for why and how.
 */
const plugin = require('tailwindcss/plugin');

module.exports = {
	darkMode: 'class',
	theme: {
		extend: {
			colors: ${JSON.stringify(colors, null, '\t').replace(/\n/g, '\n\t\t\t')}
		}
	},
	plugins: [
		plugin(({ addBase }) =>
			addBase({
				':root': {
${block(light)}
				},
				'.dark': {
					'color-scheme': 'dark',
${block(dark)}
				},
				// Form fields have no colour class of their own, so under color-scheme: dark
				// the browser paints them its own grey. Give them the page's surfaces, in
				// the base layer, where any utility class still wins.
				'input:not([type="checkbox"]):not([type="radio"]), textarea, select': {
					'background-color': 'rgb(var(--c-white))',
					color: 'rgb(var(--c-gray-900))'
				},
				'::placeholder': { color: 'rgb(var(--c-gray-500))' }
			})
		)
	]
};
`;
writeFileSync(new URL('../packages/doichain/tailwind-preset.cjs', import.meta.url), out);
console.log(`tailwind-preset.cjs: ${Object.keys(light).length} colours, light and dark`);
